apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090   # prometheus container name on docker network
    isDefault: true               # set as default data source in Grafana
    editable: true
